yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='Ключ',
        help_text='Ключ для группы в адресной строке',
    )
    description = models.TextField(
        verbose_name='Описание',
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        related_name='posts',
        verbose_name='Автор публикации',
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        Group,
        related_name='posts',
        verbose_name='Группа',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import login_required

from .forms import PostForm

from .models import Group, Post, User

from .utils import paginate_page

POST_PER_PAGE = 10


def index(request):
    post_list = Post.objects.all()
    page_obj = paginate_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginate_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginate_page(request, post_list)
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
        'author': post.author,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-sm-6">
      <div class="card text-center">
        <div class="card-header">
          Привет, Я - Олег<br>Cоавтор этого сайта
        </div>
        <div class="card-body">
          <img 
            class="card-img-top" 
            src="{% static 'img/author.png' %}" 
            alt="Card image cap" 
            style="max-height: 300px; width: auto; border-radius: 12px;"
          >
          <p></p>
          <h5 class="card-title">Тут я размещу информацию о себе, используя свои умения верстать.</h5>
          <p class="card-text">Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.</p>
          <a href="https://github.com/discoveryline" class="btn btn-primary">Go to GitHub</a>
        </div>
        <div class="card-footer text-muted"></div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card text-center">
        <div class="card-header">
          Привет, Я - ЯП<br>Cоавтор этого сайта
        </div>
        <div class="card-body">
          <img 
            class="card-img-top" 
            src="{% static 'img/logo.png' %}" 
            alt="Card image cap" 
            style="height: 300px; width: auto; border-radius: 12px;"
          >
          <p></p>
          <h5 class="card-title">Тут я размещу информацию о себе, используя свои умения верстать.</h5>
          <p class="card-text">Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста..</p>
          <a href="https://practicum.yandex.ru/" class="btn btn-primary">Go to Yandex</a>
        </div>
        <div class="card-footer text-muted"></div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %} Yatube {% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли :(
        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/forms/fields_if_form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
      {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/forms/fields_in_post_form.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
          href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}"
          >  
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
              href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% endwith %}
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактирование поста
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/forms/fields_if_form_errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% include 'includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description|linebreaksbr }}
  </p>
  <br>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>    
      <a href="{% url 'posts:post_detail' post.pk %}">
        подробная информация
      </a>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}  
  <h1>Последние обновления на сайте</h1>
  <br>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">
        подробная информация
      </a>
    </article>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы "{{ post.group.title }}"
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}  
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }} <br>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text|linebreaksbr }}</p>
      {% if author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>  
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}  
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  <br>
  {% for post in page_obj %}
    <article>
      <ul>
        {% comment %} <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li> 
        {% endcomment %}
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">
        подробная информация
      </a>
    </article>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы "{{ post.group.title }}"
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/forms/fields_if_form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include 'includes/forms/fields_in_post_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}Пароль изменён{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Смена пароля
          </div>
          <div class="card-body">
            {% include 'includes/users/fields_if_form_errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% include 'includes/users/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Новый пароль{% endblock %}

{% block content %}
  {% if validlink %}
    {% include 'includes/forms/fields_if_form_errors.html' %}
    <form method="post"
      {% if action_url %}
        action="{% url action_url %}"
      {% endif %}
    >
      {% csrf_token %}
      {% include 'includes/forms/fields_in_post_form.html' %}
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Назначить новый пароль
        </button>
      </div>
    </form>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            {% include 'includes/forms/fields_if_form_errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% include 'includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/forms/fields_if_form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}